export const seededSizes: SizeRecord[] = [
  {
    id: "size_13_round",
    name: '13"',
    shape: "round",
    diameterInches: 13,
    surfaceAreaSqIn: Math.PI * Math.pow(13 / 2, 2),
    defaultServings: 3,
    defaultDoughWeight: 16,
  },
  {
    id: "size_15_round",
    name: '15"',
    shape: "round",
    diameterInches: 15,
    surfaceAreaSqIn: Math.PI * Math.pow(15 / 2, 2),
    defaultServings: 4,
    defaultDoughWeight: 20,
  },
  {
    id: "size_10x14_rect",
    name: '10x14"',
    shape: "rectangle",
    lengthInches: 14,
    widthInches: 10,
    surfaceAreaSqIn: 140,
    defaultServings: 3.5,
    defaultDoughWeight: 18,
  },
];
